// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBecEltUk1Qz3TB_JbUVVvMYrJEL6CsQNs',
    appId: '1:898886160105:web:75adff5edfe06166afaa78',
    messagingSenderId: '898886160105',
    projectId: 'shake-image-pick',
    authDomain: 'shake-image-pick.firebaseapp.com',
    storageBucket: 'shake-image-pick.appspot.com',
    measurementId: 'G-LWEPKQE9PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzv9a1Em0BIFmDyLEHbbf_yi_S5cQc0o4',
    appId: '1:898886160105:android:30da40ba4de5a79eafaa78',
    messagingSenderId: '898886160105',
    projectId: 'shake-image-pick',
    storageBucket: 'shake-image-pick.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvRCx6EqKybd5H41Ba9qcXLSdZLSnm9hE',
    appId: '1:898886160105:ios:120e6214dc997249afaa78',
    messagingSenderId: '898886160105',
    projectId: 'shake-image-pick',
    storageBucket: 'shake-image-pick.appspot.com',
    iosBundleId: 'com.example.shakingpic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvRCx6EqKybd5H41Ba9qcXLSdZLSnm9hE',
    appId: '1:898886160105:ios:120e6214dc997249afaa78',
    messagingSenderId: '898886160105',
    projectId: 'shake-image-pick',
    storageBucket: 'shake-image-pick.appspot.com',
    iosBundleId: 'com.example.shakingpic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBecEltUk1Qz3TB_JbUVVvMYrJEL6CsQNs',
    appId: '1:898886160105:web:f78a20575c85c2d9afaa78',
    messagingSenderId: '898886160105',
    projectId: 'shake-image-pick',
    authDomain: 'shake-image-pick.firebaseapp.com',
    storageBucket: 'shake-image-pick.appspot.com',
    measurementId: 'G-LD281P4DEW',
  );
}
