// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiiRr8wJAzvFFHWrUI3rTjDytZjSvdP88',
    appId: '1:390008855099:web:162840e5a93491e75cda1e',
    messagingSenderId: '390008855099',
    projectId: 'capture-image-e5a7f',
    authDomain: 'capture-image-e5a7f.firebaseapp.com',
    storageBucket: 'capture-image-e5a7f.appspot.com',
    measurementId: 'G-VM1GEYZBLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0yyF-bf3kkVyL240oxqJSfzR3apYPHtU',
    appId: '1:390008855099:android:322c919367b4e5f65cda1e',
    messagingSenderId: '390008855099',
    projectId: 'capture-image-e5a7f',
    storageBucket: 'capture-image-e5a7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByAE6Yoqmjzx9Xc3L37aNbo8Fu88Kjwmo',
    appId: '1:390008855099:ios:b481558c6e58ccf75cda1e',
    messagingSenderId: '390008855099',
    projectId: 'capture-image-e5a7f',
    storageBucket: 'capture-image-e5a7f.appspot.com',
    iosBundleId: 'com.example.shakingpic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByAE6Yoqmjzx9Xc3L37aNbo8Fu88Kjwmo',
    appId: '1:390008855099:ios:b481558c6e58ccf75cda1e',
    messagingSenderId: '390008855099',
    projectId: 'capture-image-e5a7f',
    storageBucket: 'capture-image-e5a7f.appspot.com',
    iosBundleId: 'com.example.shakingpic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiiRr8wJAzvFFHWrUI3rTjDytZjSvdP88',
    appId: '1:390008855099:web:b61f3f195fa328295cda1e',
    messagingSenderId: '390008855099',
    projectId: 'capture-image-e5a7f',
    authDomain: 'capture-image-e5a7f.firebaseapp.com',
    storageBucket: 'capture-image-e5a7f.appspot.com',
    measurementId: 'G-1ZZ1PFGDML',
  );

}